### ISSUE TITLE
[1.1.2] For Clients, anytime a masked is killed, it spawns several non-interactable old phones that reduce FPS

### ISSUE THREAD

**Issue by Silhygames** [GoldenKittenPlays/GetLootForKills#1] opened 2023-12-23 23:32 UTC
Was using this in a multiplayer lobby on 12/22, and found that whenever a masked was killed, it dropped the old phone loot as per the config default (no problem), but for clients, it dropped several instances of phones that were not interactable. This caused a lot of fps drops due to the sheer amount of phones being generated per masked. 

![image](https://github.com/GoldenKittenPlays/GetLootForKills/assets/154468048/39ec187b-b287-435b-ae1d-f579e192fdb8)
![image](https://github.com/GoldenKittenPlays/GetLootForKills/assets/154468048/7c8411f2-0813-48d3-b0db-e1975fe2f26e)

We were using a rather large modpack, but as far as possible conflicts, I think the only other mod that really affects the masked was Masked Enemy Overhaul.

Also, I realize 1.1.3 has been released since, but I didn't see a changelog on the modpage, and I'm not sure if this has been noticed, so I thought to report it.

**Comment by GoldenKittenPlays** [comment] 2023-12-24 00:47
Thank you for the heads up and you were right that it was an issue and sadly since i do not have anyone to test but myself I only recently figured it out. I think i did fix the issue but be sure to let me know if not I would be happy to fix it.

**Comment by GoldenKittenPlays** [comment] 2023-12-24 01:58
Sorry it seems it is still an issue I am seeing if I can fix it now and once again thanks for the heads up

**Comment by GoldenKittenPlays** [comment] 2023-12-25 13:10
I think the issue is resolved but now I wait for people to play it and give me feedback. I think it is good though. Happy playing

**Comment by GoldenKittenPlays** [comment] 2023-12-30 09:16
I have not received any reports so I am closing the issue. Thank you for your interest nya

**Closed as completed by GoldenKittenPlays** 2023-12-30 09:16 UTC
Labels: bug
